# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - hip
      - shoulder
      - elbow
      - elbow_2
      - elbow_3
      - elbow_4
      - wrist
    action_ns: follow_joint_trajectory
    default: true